#f = open("file.txt", "a")
#f.write("Now the file has more content!")
#f.close()

#f = open("file.txt", "w")
#f.write("Woops!")
#f.close()
#f=open("file.txt","r")
#print(f.read())

f = open("file.txt", "w")
f.write("Woops!")

f=open("file.txt","r")
print(f.read())
f = open("file.txt", "a")
f.write("Now the file has more content!")
#f=open("file.txt","w")
#print(f.read())
f.close()